### ISSUE TITLE
typescript dependency

### ISSUE THREAD

**Issue by gadkadosh** [vscode-langservers/vscode-css-languageserver-bin#1]
typescript seems to be required as a dependency and not devDependency. Installing with --global misses it and the binary fails to run:

> module.js:557
>     throw err;
>     ^
> 
> Error: Cannot find module 'typescript'
>     at Function.Module._resolveFilename (module.js:555:15)
>     at Function.Module._load (module.js:482:25)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/vscode-html-languageserver-bin/modes/javascriptMode.js:10:10)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>

**Comment by DeltaEvo** [comment]
It's the wrong project, this issue if for the html language server.
Anyway thanks, fixed in https://github.com/vscode-langservers/vscode-html-languageserver-bin/commit/54c51a8350ddb5417fc0be88df73c1afebe53b46
Run ` npm update --global vscode-html-languageserver-bin` to update 😄
