### ISSUE TITLE
psuedo-selectors doc doesn't display correctly

### ISSUE THREAD

**Issue by ar1a** [vscode-langservers/vscode-css-languageserver-bin#2]
Hi there! 

I was messing around with the language server and noticed the doc doesn't work quite right! Here's a screenshot:
![image](https://user-images.githubusercontent.com/8436007/41201694-cc879ec0-6cff-11e8-969e-a1b7b85cf4f8.png)

**Comment by ar1a** [comment]
![image](https://user-images.githubusercontent.com/8436007/41201700-f7478e04-6cff-11e8-9c4b-383a8cf84eb6.png)

**Comment by DeltaEvo** [comment]
This issue should be reported to https://github.com/Microsoft/vscode-css-languageservice
